appointment/urls.py
from django.urls import path

from appointment import views
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'appointment'

urlpatterns = [

    path('', views.welcome, name="appointment-welcome"),
    path('home/', HomePageView.as_view(), name='home'),
    path('service', ServiceView.as_view(), name='service'),
    path('doctor/appointment/create', AppointmentCreateView.as_view(), name='doctor-appointment-create'),
    path('doctor/appointment/', AppointmentListView.as_view(), name='doctor-appointment'),
    path('<pk>/delete/', AppointmentDeleteView.as_view(), name='delete-appointment'),
    path('<pk>/patient/delete', PatientDeleteView.as_view(), name='delete-patient'),
    path('patient-take-appointment/<pk>', TakeAppointmentView.as_view(), name='take-appointment'),
    path('search/', SearchView.as_view(), name='search'),
    path('patient/', PatientListView.as_view(), name='patient-list'),
    path('aboutus/', views.aboutus, name="appointment-aboutus"),
    path('wellness/', views.wellness, name="appointment-wellness"),
    path('welcome/', views.welcome, name="appointment-welcome"),
    path('fitness/', views.fitness, name="appointment-fitness"),
    path('show/', views.show, name="appointment-show"),
    path('emp', views.emp, name="appointment-emp"),
    path('edit/<int:id>', views.edit, name="appointment-edit"),
    path('update/<int:id>', views.update, name="appointment-update"),
    path('delete/<int:id>', views.destroy, name="appointment-delete"),

    #path('patients/<int:appointment_id>', PatientPerAppointmentView.as_view(), name='patient-list'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor_appointment_system/urls.py
"""
doctor_appointment_system URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from appointment.views import PatientListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),
    path('', include('store.urls')),
    #path('', include('calorie.urls')),
    path('', include('django.contrib.auth.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Leave as empty string for base url
    path('', views.store, name="store"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('store/', views.store, name="store"),
    path('thankyou/', views.thankyou, name="thankyou"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('carona/', views.carona, name="carona"),

]

appointment/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from accounts.models import User

department = (
    ('Dentistry', "Dentistry"),
    ('Cardiology', "Cardiology"),
    ('ENT Specialists', "ENT Specialists"),
    ('Astrology', 'Astrology'),
    ('Neuroanatomy', 'Neuroanatomy'),
    ('Blood Screening', 'Blood Screening'),
    ('Eye Care', 'Eye Care'),
    ('Physical Therapy', 'Physical Therapy'),
)


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
    qualification_name = models.CharField(max_length=100)
    institute_name = models.CharField(max_length=100)
    hospital_name = models.CharField(max_length=100)
    department = models.CharField(choices=department, max_length=100)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.full_name

    # def get_absolute_url(self):
    # return reverse('appointment:delete-appointment', kwargs={'pk': self.pk})


class TakeAppointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    message = models.TextField()
    phone_number = models.CharField(max_length=120)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.full_name


class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

appointment/forms.py
from django import forms
from .models import Appointment, TakeAppointment


class CreateAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].label = "Full Name"
        self.fields['department'].label = "Department"
        self.fields['start_time'].label = "Start Time"
        self.fields['hospital_name'].label = "Hospital Name"
        self.fields['qualification_name'].label = "Qualification"
        self.fields['institute_name'].label = "Institute"

        self.fields['full_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Full Name',
            }
        )

        self.fields['department'].widget.attrs.update(
            {
                'placeholder': 'Select Your Service',
            }
        )

        self.fields['start_time'].widget.attrs.update(
            {
                'placeholder': 'Ex : 9 AM',
            }
        )
        self.fields['end_time'].widget.attrs.update(
            {
                'placeholder': 'Ex: 5 PM',
            }
        )
        self.fields['location'].widget.attrs.update(
            {
                'placeholder': 'Ex : India',
            }
        )

        self.fields['hospital_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Hospital Name',
            }
        )

        self.fields['qualification_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : MBBS, BDS',
            }
        )

        self.fields['institute_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : OSMANIA',
            }
        )

    class Meta:
        model = Appointment
        fields = ['full_name','department', 'start_time', 'end_time', 'location',
                  'hospital_name', 'qualification_name', 'institute_name']

    def is_valid(self):
        valid = super(CreateAppointmentForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(CreateAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment


class TakeAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TakeAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['appointment'].label = "Choose Your Doctor"
        self.fields['full_name'].label = "Full Name"
        self.fields['phone_number'].label = "Phone Number"
        self.fields['message'].label = "Message"

        self.fields['appointment'].widget.attrs.update(
            {
                'placeholder': 'Choose Your Doctor',
            }
        )

        self.fields['full_name'].widget.attrs.update(
            {
                'placeholder': 'Write Your Name',
            }
        )

        self.fields['phone_number'].widget.attrs.update(
            {
                'placeholder': 'Enter Phone Number',
            }
        )
        self.fields['message'].widget.attrs.update(
            {
                'placeholder': 'Write a short message',
            }
        )

    class Meta:
        model = TakeAppointment
        fields = ['appointment', 'full_name', 'phone_number', 'message']

    def is_valid(self):
        valid = super(TakeAppointmentForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(TakeAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment

appointment/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from accounts.models import User
from .decorators import user_is_patient, user_is_doctor
from django.views.generic import TemplateView, UpdateView, CreateView, ListView, DetailView, DeleteView
from django.views.generic.edit import DeleteView, UpdateView
from accounts.forms import PatientProfileUpdateForm, DoctorProfileUpdateForm
from .forms import CreateAppointmentForm, TakeAppointmentForm
from .models import Appointment, TakeAppointment


def aboutus(request):
    return render(request, 'appointment/aboutus.html')


def wellness(request):
    return render(request, 'appointment/wellness.html')


def fitness(request):
    return render(request, 'appointment/fitness.html')


def welcome(request):
    return render(request, 'appointment/welcome.html')


class EditPatientProfileView(UpdateView):
    model = User
    form_class = PatientProfileUpdateForm
    context_object_name = 'patient'
    template_name = 'accounts/patient/edit-profile.html'
    success_url = reverse_lazy('accounts:patient-profile-update')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_patient)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        # context = self.get_context_data(object=self.object)
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        print(obj)
        if obj is None:
            raise Http404("Patient doesn't exists")
        return obj


class TakeAppointmentView(CreateView):
    template_name = 'appointment/take_appointment.html'
    form_class = TakeAppointmentForm
    extra_context = {
        'title': 'Take Appointment'
    }
    success_url = reverse_lazy('appointment:home')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'patient':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TakeAppointmentView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class EditDoctorProfileView(UpdateView):
    model = User
    form_class = DoctorProfileUpdateForm
    context_object_name = 'doctor'
    template_name = 'accounts/doctor/edit-profile.html'
    success_url = reverse_lazy('accounts:doctor-profile-update')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_doctor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        # context = self.get_context_data(object=self.object)
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        print(obj)
        if obj is None:
            raise Http404("Patient doesn't exists")
        return obj


class AppointmentCreateView(CreateView):
    template_name = 'appointment/appointment_create.html'
    form_class = CreateAppointmentForm
    extra_context = {
        'title': 'Post New Appointment'
    }
    success_url = reverse_lazy('appointment:doctor-appointment')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'doctor':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AppointmentCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AppointmentListView(ListView):
    model = Appointment
    template_name = 'appointment/appointment.html'
    context_object_name = 'appointment'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_doctor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id).order_by('-id')


class PatientListView(ListView):
    model = TakeAppointment
    context_object_name = 'patients'
    template_name = "appointment/patient_list.html"

    def get_queryset(self):
        return self.model.objects.filter(appointment__user_id=self.request.user.id).order_by('-id')


class PatientDeleteView(DeleteView):
    model = TakeAppointment
    success_url = reverse_lazy('appointment:patient-list')


class AppointmentDeleteView(DeleteView):
    """
       For Delete any Appointment created by Doctor
    """
    model = Appointment
    success_url = reverse_lazy('appointment:doctor-appointment')


class HomePageView(ListView):
    paginate_by = 9
    model = Appointment
    context_object_name = 'home'
    template_name = "home.html"

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')


class ServiceView(TemplateView):
    template_name = 'appointment/service.html'


class SearchView(ListView):
    paginate_by = 6
    model = Appointment
    template_name = 'appointment/search.html'
    context_object_name = 'appointment'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         department__contains=self.request.GET['department'])

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,'appointment/index.html',{'form':form})


def show(request):
    employees = Employee.objects.all()
    return render(request, "appointment/show.html", {'employees': employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'appointment/edit.html', {'employee': employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})


def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

templates/appointment/aboutus.html
{% load static %}
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="{% static 'astyle.css' %}">
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" >Fitlab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/home">Health</a></li>
                        <li class="nav-item"><a class="nav-link" href="/store">Wellness</a></li>
                        <li class="nav-item"><a class="nav-link" href="/user">Fitness</a></li>
                        <li class="nav-item"><a class="nav-link" href="/aboutus">AboutUs</a></li>
                        <li class="nav-item"><a class="nav-link" href="/doctor/register">Doctor Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="/patient/register">Patient Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
<div class="about-section">
  <h1>About Us FitLab</h1>
</div>
<h2 style="text-align:center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
    <img src="{{ '/media/about.jpg' }}" alt="Mike" style="width:100%">
      <div class="container">
        <h2>Susheel</h2>
        <p class="title">Team Lead </p>
        <p> Developer </p>
		<p>sanagapallisaisusheelgupta@gmail.com</p>
        <p>190031462</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="{{ '/media/about.jpg' }}" alt="Mike" style="width:100%">
      <div class="container">
        <h2>neehal</h2>
        <p class="title">Team Member </p>
        <p> Developer </p>
        <p>shaikneehal54@gmail.com</p>
        <p>190031500</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="{{ '/media/about.jpg' }}" alt="Mike" style="width:100%">
      <div class="container">
        <h2>Nikhil</h2>
        <p class="title">Team Member </p>
        <p> Developer </p>
        <p>nikhillanka2002@gmail.com</p>
        <p>190030935</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>


</div>
{% block content %}{% endblock %}
</body>
</html>

templates/appointment/appointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Appointment List{% endblock %}
{% block content %}
    <section class="dentist-area section-padding-40-0">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="section-heading text-center">
            <h3>{{ request.user.first_name }}'s Appointment/s</h3>
            <div class="line"></div>
          </div>
        </div>
      </div>
      <div class="row">
          {% for apt in appointment %}
        <div class="col-12 col-sm-6 col-md-4">
          <br></br>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <center>
                                            <th scope="col">
                                                <div class="container">
                                                    <div class="card" style="width:400px">
                                                            <div class="card-body">
                                                                <h4 class="card-title">Information</h4>
                                                                     <ol>
                                                                         <li><span>Name :</span><span>{{ apt.full_name }}</span></li>
                                                                         <li><span>Specialization :</span><span>{{ apt.department }}</span></li>
                                                                         <li><span>Qualification :</span><span>{{ apt.qualification_name }}</span></li>
                                                                         <li><span>Start time :</span><span>{{ apt.start_time }}</span></li>
                                                                         <li><span>End Time :</span><span>{{ apt.end_time }}</span></li>
                                                                         <li><span>Hosipital name :</span><span>{{ apt.hospital_name }}</span></li>
                                                                         <li><span>Address :</span><span>{{ apt.location }}</span></li>
                                                                        <li></li>
                                                                     </ol>
                                                                <a href="{% url 'appointment:delete-appointment' apt.id %}" class="btn btn-primary">Remove Appointment</a>
                                                            </div>
                                                    </div>
                                                </div>
                                            </th>
                                        </center>
                                    </tr>
                                </thead>
                            </table>
        </div>
      {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

templates/appointment/appointment_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Appointment Delete{% endblock %}
{% block content %}
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 mb-5 mb-lg-0">
                <center>
                    <h4 class="highlight">Are you sure you want to delete {{ object.full_name }}'s Appointment?</h4>
                </center>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    <img style="height: 400px; width: 450px" src="{% static 'img/example.jpg' %}">
                    </br>
                    </br>
                    <center><input class="btn btn-danger" type="submit" value="Delete">
                    </center>
                </form>
                </br>
            </div>
        </div>
    </div>
{% endblock %}
</body>

templates/appointment/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
{% block content %}{% endblock %}
</body>
</html>

templates/appointment/search.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


    <div class="breadcumb-area bg-img bg-gradient-overlay"  style="background-image: url('{% static 'img/bg-img/13.jpg' %}');">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">

             <form id="job-main-form" method="get" action="" class="search-doctor-form">
                    <div class="row mb-5">


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location"
                                   class="form-control form-control-lg" placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <select id="department" name="department" class="form-control">
                                 <option style="display: none;" >Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select>
                        </div>


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Doctor
                            </button>
                        </div>
                    </div>
                </form>


        </div>
      </div>
    </div>
  </div>



    <section class="dentist-area section-padding-50-0">

        <div class="container">







            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">


                        <h3>We have found {{ appointment.count }} doctor/s. </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in appointment %}
                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 500px; width: 600px" src="{{ apt.image.url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-gradient-overlay">
                                    {% if request.user.is_authenticated and request.user.role == 'patient' %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>
                                            AT {{ apt.location }} <i class="fa fa-th"></i>
                                            <a href="{% url 'appointment:take-appointment' apt.id %}"> Take
                                                Appointment</a>

                                        </p>
                                    {% elif request.user.is_authenticated and request.user.role == 'doctor' %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>AT {{ apt.location }}


                                        </p>

                                    {% else %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>AT {{ apt.location }}



                                        </p>

                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>


{% endblock %}