accounts/urls.py
from django.urls import path
from .views import *
from appointment.views import *

app_name = "accounts"

urlpatterns = [
    path('patient/register', RegisterPatientView.as_view(), name='patient-register'),
    path('patient/profile/update/', EditPatientProfileView.as_view(), name='patient-profile-update'),
    path('doctor/register', RegisterDoctorView.as_view(), name='doctor-register'),
    path('doctor/profile/update/', EditDoctorProfileView.as_view(), name='doctor-profile-update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

appointment/urls.py
from django.urls import path

from appointment import views
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'appointment'

urlpatterns = [

    path('', views.welcome, name="appointment-welcome"),
    path('home/', HomePageView.as_view(), name='home'),
    path('service', ServiceView.as_view(), name='service'),
    path('doctor/appointment/create', AppointmentCreateView.as_view(), name='doctor-appointment-create'),
    path('doctor/appointment/', AppointmentListView.as_view(), name='doctor-appointment'),
    path('<pk>/delete/', AppointmentDeleteView.as_view(), name='delete-appointment'),
    path('<pk>/patient/delete', PatientDeleteView.as_view(), name='delete-patient'),
    path('patient-take-appointment/<pk>', TakeAppointmentView.as_view(), name='take-appointment'),
    path('search/', SearchView.as_view(), name='search'),
    path('patient/', PatientListView.as_view(), name='patient-list'),
    path('aboutus/', views.aboutus, name="appointment-aboutus"),
    path('wellness/', views.wellness, name="appointment-wellness"),
    path('welcome/', views.welcome, name="appointment-welcome"),
    path('fitness/', views.fitness, name="appointment-fitness"),
    path('show/', views.show, name="appointment-show"),
    path('emp', views.emp, name="appointment-emp"),
    path('edit/<int:id>', views.edit, name="appointment-edit"),
    path('update/<int:id>', views.update, name="appointment-update"),
    path('delete/<int:id>', views.destroy, name="appointment-delete"),

    #path('patients/<int:appointment_id>', PatientPerAppointmentView.as_view(), name='patient-list'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor_appointment_system/urls.py
"""
doctor_appointment_system URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from appointment.views import PatientListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),
    path('', include('store.urls')),
    #path('', include('calorie.urls')),
    path('', include('django.contrib.auth.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Leave as empty string for base url
    path('', views.store, name="store"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('store/', views.store, name="store"),
    path('thankyou/', views.thankyou, name="thankyou"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('carona/', views.carona, name="carona"),

]

templates/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">

  <title>FITLAB {% block title %} {% endblock %}</title>

  <link rel="icon" href="{% static 'img/core-img/favicon.png' %}">

  <link rel="stylesheet" href="{% static 'style.css' %}">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% block styles %} {% endblock %}

</head>

<body>
  {% include 'nav.html' %}
      {% block content %}
      {% endblock  %}

  <footer class="footer-area bg-img bg-gradient-overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-footer-widget">
            <a href="./index.html" class="d-block mb-4"><img src="{% static 'img/logo1.png' %}" alt=""></a>
            <div class="footer-contact">
                 <p> Welcome to FITLAB</br>One Solution for your all Your Needs Like Fitness, Wellness and Health</p>
              <p> India</p>
              <p> 9999999999</p>
              <p> info.fitlab@gmail.com</p>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <h5 class="widget-title">Opening Hours</h5>

            <ul class="opening-hours">
              <li><span>Every Day</span><span> 8:00 AM - 20:00 PM</span></li>
              <li><span>Sunday</span> <span>Closed</span></li>
            </ul>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <h5 class="widget-title">Quick Link</h5>

            <nav>
              <ul class="quick-links">
                <li><a href="/aboutus">About</a></li>
                <li><a href="#">FAQs</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Policy</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Advisors</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Legals</a></li>
              </ul>
            </nav>
          </div>
        </div>
        <div class="col-6 col-md-9 col-lg-8">
                    <div class="top-header-content">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title=""><i
                                class="fa fa-map-marker"></i> <span>INDIA</span></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title=""><i
                                class="fa fa-envelope"></i> <span>info.fitlab@gmail.com</span></a>
                    </div>
                </div>
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <div class="footer-social-info">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copywrite Area -->
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="copywrite-content">
            <p>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made by Team FITLAB</a>
</p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/dento.bundle.js' %}"></script>
  <script src="{% static 'js/default-assets/active.js' %}"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   {% block javascripts %} {% endblock %}
</body>

</html>

templates/home.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" style="color:white;">Fitlab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/welcome">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/home">Health</a></li>
                        <li class="nav-item"><a class="nav-link" href="/wellness">Wellness</a></li>
                        <li class="nav-item"><a class="nav-link" href="/user">Fitness</a></li>
                        <li class="nav-item"><a class="nav-link" href="/aboutus">AboutUs</a></li>
                        <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
 {% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
  <section class="welcome-area">
    <div class="welcome-slides owl-carousel">
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax"  style="background-image: url('{% static 'img/bg-img/1.jpg' %}');">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInUp" data-delay="100ms">We Believe Everyone Should Have Easy Access To Great Health Care</h2>
                <div class="welcome-btn-group">
                    <form id="job-main-form" method="get" action="{% url 'appointment:search' %}" class="search-doctor-form">
                    <div class="row mb-5">
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <select id="department" name="department" class="form-control">
                                <option style="display: none;" >Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select>
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">

                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Doctor
                            </button>
                        </div>
                    </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax"  style="background-image: url('{% static 'img/bg-img/2.jpg' %}');">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInDown" data-delay="100ms">We Believe Everyone Should Have Easy Access To Great Health Care</h2>
                <div class="welcome-btn-group">
                    <form id="job-main-form" method="get" action="{% url 'appointment:search' %}" class="search-doctor-form">
                    <div class="row mb-5">
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                                <select id="department" name="department" class="form-control">
                                <option style="display: none;" >Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select>
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Doctor
                            </button>
                        </div>
                    </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
    <section class="dentist-area section-padding-35-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center">
                         </br>
                        <h3 class="lead">Available Doctors </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for apt in home %}
                    <div class="col-12 col-sm-6 col-md-4">
                            <br></br>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <center>
                                            <th scope="col">
                                                <div class="container">
                                                    <div class="card" style="width:400px">
                                                            <div class="card-body">
                                                                <h4 class="card-title">Information</h4>
                                                                     <ol>
                                                                         <li><span>Name :</span><span>{{ apt.full_name }}</span></li>
                                                                         <li><span>Department :</span><span>{{ apt.department }}</span></li>
                                                                         <li><span>Qualification :</span><span>{{ apt.qualification_name }}</span></li>
                                                                         <li><span>Institution :</span><span>{{ apt.institute_name }}</span></li>
                                                                         <li><span>Start time :</span><span>{{ apt.start_time }}</span></li>
                                                                         <li><span>End Time :</span><span>{{ apt.end_time }}</span></li>
                                                                         <li><span>Hosipital name :</span><span>{{ apt.hospital_name }}</span></li>
                                                                         <li><span>Address :</span><span>{{ apt.location }}</span></li>
                                                                        <li></li>
                                                                     </ol>
                                                                 <i style="font-size:24px" class="fa">&#xf073;</i>
                                                                <a href="{% url 'appointment:take-appointment' apt.id %}" class="btn btn-primary">Make Appointment</a>
                                                            </div>
                                                    </div>
                                                </div>
                                            </th>
                                        </center>
                                    </tr>
                                </thead>
                            </table>
                    </div>
            </div>
                {% endfor %}
                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/nav.html
{% load static %}
    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <nav class="classy-navbar justify-content-between" id="dentoNav">
                    <a class="nav-brand" href="{% url 'appointment:home' %}"><img src="{% static 'img/logo1.png' %}" alt="">
                    </a>
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>
                    <div class="classy-menu">
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>
                        <div class="classynav">
                            <ul id="nav">
                                <li><a href="{% url 'appointment:home' %}">Home</a></li>
                                <li><a href="{% url 'appointment:service' %}">Services</a></li>
                                <li><a href="{% url 'accounts:doctor-register' %}"> <b>DOCTOR </b></a></li>
                                <li><a href="{% url 'accounts:patient-register' %}"> <b>PATIENT </b></a></li>
                                {% if request.user.is_authenticated and request.user.role == 'doctor' %}
                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'accounts:doctor-profile-update'  %}"> EDIT PROFILE</a></li>
                                            <li><a href="{% url 'appointment:patient-list' %}"> PATIENTS</a></li>
                                            <li><a href="{% url 'appointment:doctor-appointment' %}">  APPOINTMENTS</a></li>
                                            <li><a href="{% url 'appointment:doctor-appointment-create' %}"> CREATE APPOINTMENT</a></li>
                                            <li><a href="{% url 'accounts:logout' %}"> LOGOUT</a></li>
                                        </ul>
                                    </li>
                             {% elif request.user.is_authenticated and request.user.role == 'patient' %}
                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'accounts:patient-profile-update'  %}"> EDIT PROFILE</a></li>
                                            <li><a href="{% url 'accounts:logout' %}"> LOGOUT</a></li>
                                        </ul>
                                    </li>
                              {% else %}
                                    <li>
                                        <a href="{% url 'accounts:login' %}">
                                            <span class="glyphicon glyphicon-user"> login</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>